In [2]:
import numpy as np
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor 
from sklearn.ensemble import RandomForestRegressor

# Playing with the train data

In [3]:
disease_X_train= np.loadtxt('disease_X_train.txt')

In [4]:
len(disease_X_train)

353

In [5]:
disease_y_train= np.loadtxt('disease_y_train.txt')

In [6]:
disease_y_train

array([144., 150., 280., 125.,  59.,  65., 281., 277., 167.,  90.,  72.,
       178.,  88., 270., 101., 197.,  97.,  53.,  71., 262.,  52., 102.,
       166., 189., 173., 220., 206.,  97.,  60.,  61., 242., 121., 128.,
       104., 265., 132., 283., 174., 129., 257., 137.,  63.,  93., 232.,
       208., 261., 179., 258., 262.,  51., 237.,  71., 139., 268.,  69.,
       317., 249., 154., 192., 116.,  81., 122., 259., 191., 292.,  55.,
       107., 210.,  91., 253.,  85., 252.,  59.,  78., 200.,  78., 245.,
       175.,  42., 127.,  53.,  94., 104., 199., 265., 281., 248., 257.,
       215., 303., 170.,  59., 277., 209., 138., 198., 124.,  96., 288.,
       225., 265., 101.,  55., 198.,  51., 252.,  64., 220., 131., 212.,
       142., 103., 155., 121.,  86., 111.,  65., 131.,  51., 128., 141.,
        48., 109., 178.,  88.,  84., 216., 150.,  60.,  96., 190.,  74.,
       279., 182., 160., 245., 276., 174., 180., 150., 196., 138.,  97.,
       246., 321., 308., 109.,  69., 182., 258., 16

# Playing with Test Data

In [7]:
disease_X_test= np.loadtxt('disease_X_test.txt')

In [8]:
disease_X_test

array([[ 0.04534098, -0.04464164, -0.00620595, -0.01599898,  0.1250187 ,
         0.1251981 ,  0.019187  ,  0.03430886,  0.03243232, -0.0052198 ],
       [ 0.09256398, -0.04464164,  0.03690653,  0.02187239, -0.02496016,
        -0.01665815,  0.00077881, -0.03949338, -0.02251653, -0.02178823],
       [ 0.06350368,  0.05068012, -0.00405033, -0.01255612,  0.10300346,
         0.04878988,  0.05600338, -0.00259226,  0.08449153, -0.01764613],
       [ 0.09619652, -0.04464164,  0.0519959 ,  0.07926471,  0.05484511,
         0.03657709, -0.07653559,  0.14132211,  0.09864806,  0.06105391],
       [ 0.01264814,  0.05068012, -0.02021751, -0.00222757,  0.03833367,
         0.05317395, -0.00658447,  0.03430886, -0.00514219, -0.00936191],
       [ 0.0090156 , -0.04464164, -0.02452876, -0.02632753,  0.0988756 ,
         0.0941964 ,  0.07072993, -0.00259226, -0.02139531,  0.00720652],
       [-0.00914709,  0.05068012,  0.17055523,  0.01498668,  0.03007796,
         0.03375875, -0.02131102,  0.03430886

In [9]:
disease_y_test= np.loadtxt('disease_y_test.txt')

In [10]:
disease_y_test

array([219.,  70., 202., 230., 111.,  84., 242., 272.,  94.,  96.,  94.,
       252.,  99., 297., 135.,  67., 295., 264., 170., 275., 310.,  64.,
       128., 232., 129., 118., 263.,  77.,  48., 107., 140., 113.,  90.,
       164., 180., 233.,  42.,  84., 172.,  63.,  48., 108., 156., 168.,
        90.,  52., 200.,  87.,  90., 258., 136., 158.,  69.,  72., 171.,
        95.,  72., 151., 168.,  60., 122.,  52., 187., 102., 214., 248.,
       181., 110., 140., 202., 101., 222., 281.,  61.,  89.,  91., 186.,
       220., 237., 233.,  68., 190.,  96.,  72., 153.,  98.,  37.,  63.,
       184.])

# Question 1

In [11]:
print(len(disease_y_test))

89


In [12]:
mean_disease_y_train=np.mean(disease_y_train)

In [13]:
mean_disease_y_train

153.73654390934846

In [14]:
mean_disease_y_train_array = np.full(len(disease_y_test), mean_disease_y_train)

In [15]:
mean_disease_y_train_array

array([153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73

In [16]:
len(mean_disease_y_train_array)

89

In [17]:
mse_for_baseline = mean_squared_error(mean_disease_y_train_array, disease_y_test)

In [18]:
mse_for_baseline

5361.533457238513

# Question 2

In [19]:
Linear_model =LinearRegression(fit_intercept=True)

In [20]:
Linear_model.fit(disease_X_train,disease_y_train)

LinearRegression()

In [21]:
Linear_model_predict=Linear_model.predict(disease_X_test)

In [22]:
print(Linear_model.coef_)

[  37.90402135 -241.96436231  542.42875852  347.70384391 -931.48884588
  518.06227698  163.41998299  275.31790158  736.1988589    48.67065743]


In [23]:
Linear_model_predict

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59

In [24]:
len(Linear_model_predict)

89

In [25]:
mse_for_LinearRegression = mean_squared_error(Linear_model_predict, disease_y_test)

In [26]:
mse_for_LinearRegression

2900.193628493482

# Question 3

In [27]:
model_Decision_TreeRegressor = DecisionTreeRegressor(max_depth=5,min_samples_leaf=5,max_leaf_nodes=16) 

In [28]:
model_Decision_TreeRegressor.fit(disease_X_train,disease_y_train)

DecisionTreeRegressor(max_depth=5, max_leaf_nodes=16, min_samples_leaf=5)

In [29]:
model_Decision_TreeRegressor_perdict=model_Decision_TreeRegressor.predict(disease_X_test)

In [30]:
mse_for_Decision_TreeRegressor = mean_squared_error(model_Decision_TreeRegressor_perdict, disease_y_test)

In [31]:
mse_for_Decision_TreeRegressor

2559.2946640833115

# Question 4

In [32]:
model_Random_Forest= RandomForestRegressor(n_estimators=500,max_depth=4,random_state=2)

In [33]:
model_Random_Forest.fit(disease_X_train,disease_y_train)

RandomForestRegressor(max_depth=4, n_estimators=500, random_state=2)

In [34]:
model_Random_Forest_predict=model_Random_Forest.predict(disease_X_test)

In [35]:
Mse_model_Random_Forest=mean_squared_error(model_Random_Forest_predict,disease_y_test)

In [36]:
Mse_model_Random_Forest

2772.3961680570296